-- Create DB
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;

-- Use DB
USE hbtn_0d_usa;

-- Create table
CREATE TABLE IF NOT EXISTS states (
    id INT NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
    name VARCHAR(256) NOT NULL
);
